# LU decomposition

LU decomposes a matrix A into a lower triangular matrix and an upper triangular matrix, i.e. $A = LU$.

LU decomposition is very closely related to guassian elimination. $L$ contains the operations we perform on each row in the gaussian elimination and $U$ is the matrix after the elimination.

LU has many application areas, one is to solve linear systems $Ax = b$ where we want to solve for many b's.

Solving $Ax = b$ becomes $LUx = b$:

- find $A = LU$
- solve $Ly = b$
- solve $Ux = y$

This is easier since $L$ and $U$ are lower / upper matricies (i.e. we only need to "replace" values).

Assuming a squared matrix of size $n x n$, the computational complexity is $O(n^3)$ and space complexity is $O(n^2)$.

In [127]:
import numpy as np
import copy

In [128]:
A = np.array([[2,1,1,0],[4,3,3,1],[8,7,9,5],[6,7,9,8]]).astype(np.float)
A

array([[2., 1., 1., 0.],
       [4., 3., 3., 1.],
       [8., 7., 9., 5.],
       [6., 7., 9., 8.]])

In [129]:
def lu(A):
    U = copy.deepcopy(A)
    n, m = A.shape
    min_shape = min([n, m])
    L = np.eye(n)

    for i in range(min_shape - 1):
        for j in range(i + 1, min_shape):
            L[j, i] = U[j, i] / U[i, i]
            U[j, :] -= L[j, i] * U[i, :]
    return L, U

In [130]:
L, U = lu(A)
np.allclose(A, L @ U)

True

In [137]:
print("---------- L ----------")
print(L)
print("---------- U ----------")
print(U)

---------- L ----------
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 3. 1. 0.]
 [3. 4. 1. 1.]]
---------- U ----------
[[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 0. 2. 2.]
 [0. 0. 0. 2.]]


In [147]:
B = np.array([[1e-20, 1], [1, 1]])

In [148]:
L, U = lu(B)
np.allclose(B, L @ U)

False

In [151]:
def lu_pivot(A):
    U = copy.deepcopy(A)
    n, m = A.shape
    min_shape = min([n, m])
    L = np.eye(n)

    for i in range(min_shape - 1):
        U[i:, :].sort(axis=1)
        for j in range(i + 1, min_shape):
            
            
            L[j, i] = U[j, i] / U[i, i]
            U[j, :] -= L[j, i] * U[i, :]
    return L, U

In [152]:
Lp, Up = lu_pivot(B)
np.allclose(B, Lp @ Up)

False